language: go
sudo: false
go:
  - tip
before_install:
  - go get github.com/golang/dep/cmd/dep
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
install:
  - $GOPATH/bin/dep ensure
script:
  - cd ./cmd/fizzbuzz_go; go test -v
  - "$HOME/gopath/bin/goveralls -service=travis-ci"
matrix:
  allow_failures:
    - go: tip
branches:
  only:
    - master
